/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import java.awt.Canvas;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author DAVID
 */
public final class Vista extends javax.swing.JFrame {

    private final Modelo modeloJuego;
    private Controlador miControlador;
    
    public Vista(Modelo miModelo) {
        modeloJuego = miModelo;
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        AsignarEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PnaelCanvas = new javax.swing.JPanel();
        Lienzo = new java.awt.Canvas();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PnaelCanvas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        Lienzo.setPreferredSize(new java.awt.Dimension(648, 388));

        javax.swing.GroupLayout PnaelCanvasLayout = new javax.swing.GroupLayout(PnaelCanvas);
        PnaelCanvas.setLayout(PnaelCanvasLayout);
        PnaelCanvasLayout.setHorizontalGroup(
            PnaelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        PnaelCanvasLayout.setVerticalGroup(
            PnaelCanvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Lienzo, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnaelCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PnaelCanvas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    public Controlador getControlador() {
        if (miControlador == null) {
            miControlador = new Controlador(this);
        }
        return miControlador;
    }

    public Canvas getLienzo() {
        return Lienzo;
    }
    
    public Modelo getModelo() {
        return modeloJuego;
    }
   
    public void AsignarEventos() {
        Lienzo.addMouseListener(getControlador());
        Lienzo.addMouseMotionListener(getControlador());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas Lienzo;
    private javax.swing.JPanel PnaelCanvas;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
